### PR TITLE
Fix Bugs Highlighted in PE-D

### LINKED ISSUE #207: [PE-D][Tester E] Different error messages for providing invalid index for delete command
There are two cases of invalid index, either the index is below 1, or the index is too high (there is not enough person)

For index too high, the error message is shown below. This is an excellent error message since it clearly tells the problem.

However, the error message for index below 1 gives a different message, which may cause confusion of what the actual problem of the command is. Since the error message for invalid index is already made, I believe this is a low severity issue that can be fixed.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: thegrimbee/ped#7

### LINKED ISSUE #231: [PE-D][Tester B] Unhandled placeholder in developer guide
In the "Saving Data" section of the developer guide, the placeholder for how to deal with missing/corrupted data files is not replaced with the actual result. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: YosieSYX/ped#9

### LINKED ISSUE #232: [PE-D][Tester D] Can include glossary in UG
Non-technical users might not understand words such as Command Line Interface or Graphical Interface.
Including a glossary for these could make the user guide easier to understand

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: e1093051/ped#12

### LINKED ISSUE #245: [PE-D][Tester D] Potential inconsistency between DG and app behaviors
In use case for view a list of clients, if no clients have been added, system should show '"No clients added yet." I supposed when it says no clients have been added, it means address book is empty, or else I think it is not a possible scenario as sample data is given. If no clients have been added is equivalent to address book is empty, then there seems to be some inconsistency -- the app actually shows listed all persons instead.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: e1093051/ped#19

### LINKED ISSUE #248: [PE-D][Tester E] Renewal table's column name for policy number is 'Policy' instead of 'Policy Number'
As seen below, the column name for policy is 'Policy' instead of 'Policy Number'. Although from the values it is obvious that the column is supposed to show policy number, it might be clearer to name the column as 'Policy Number' instead. However, this is subjective which is why the severity is very low

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: thegrimbee/ped#12

### PR DESCRIPTION
**Pull request by MakiseKurisuX**
Issues Pertaining Delete / Edit Command (Index Error Messages):
Fixes #207 

Issues Pertaining Developer Guide:
Fixes #231 
Fixes #232 (Guys, please let me know if I am being overly judicious with adding Tags, I might have added too many)
Fixes #245 

Issues Pertaining Renewal Table:
Fixes #248

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -76,18 +76,18 @@ public static String getDetails(Throwable t) {
...
-     * Returns true if {@code s} represents a non-zero unsigned integer
+     * Returns true if {@code s} represents a plain integer, i.e. without + sign if positive, with - sign if negative.
      * e.g. 1, 2, 3, ..., {@code Integer.MAX_VALUE} <br>
      * Will return false for any other non-null string input
-     * e.g. empty string, "-1", "0", "+1", and " 2 " (untrimmed), "3 0" (contains whitespace), "1 a" (contains letters)
+     * e.g. empty string, "+1", and " +2 " (untrimmed), "3 0" (contains whitespace), "1 a" (contains letters)
      * @throws NullPointerException if {@code s} is null.
      */
-    public static boolean isNonZeroUnsignedInteger(String s) {
+    public static boolean isPlainInteger(String s) {
```
Comment (johngao122) [inline src/main/java/seedu/address/commons/util/StringUtil.java:85]: nice

File: docs/DeveloperGuide.md [hunk 2]
```diff
@@ -712,9 +707,25 @@ _{More to be added}_
...
+-   **Storage**: The component responsible for reading from and writing data to disk, ensuring data persists between sessions.
+-   **Command**: A directive issued by the insurance agent to perform actions such as adding, deleting, or updating a client.
+-   **Command Parser**: The module that interprets raw user input and converts it into a structured command object.
+-   **Command Result**: The outcome returned after a command is executed, including success confirmations or error messages.
+-   **User Preferences**: Settings that store the agent’s configuration choices for a personalized experience.
+-   **ObservableList**: A data structure that automatically notifies the UI of changes in the model, ensuring real-time updates.
+-   **Duplicate Entry**: A situation where a new client record matches an existing record based on key attributes like name and phone number.
 -   **Tag**: A custom keyword used to categorize clients for sorting and filtering.
+-   **Data Persistence**: The capability of the system to save client and policy data so that information is retained across sessions.
+-   **Mainstream OS**: Operating systems such as Windows, Linux, Unix, and MacOS.
```
Comment (johngao122) [inline docs/DeveloperGuide.md:728]: Dont forget to sync this with the user guide

**Review by johngao122 — APPROVED** [review]
LGTM

Do remember to sync the glossary with the user guide
