### PR TITLE
Fix find command wrong parameter format message

### LINKED ISSUE #134: Invalid command format message has typo and formatting error
Image

Image

Image

Weird formatting and missing space between t/friends and s/tag

### PR DESCRIPTION
**Pull request by yuyang011**
closes #134

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public class FindCommand extends Command {
             + PREFIX_PHONE + "91234567 "
             + PREFIX_POLICY + "104343 "
             + PREFIX_POLICY_TYPE + "Life "
-            + PREFIX_TAG + "friends"
+            + PREFIX_TAG + "friends "
```
Comment (MakiseKurisuX) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:58]: I like the change, didn't notice the mistake then. MB!

**Review by MakiseKurisuX — APPROVED** [review]
LGTM!
