### PR TITLE
Branch bug fix

### LINKED ISSUE #201: [PE-D][Tester C] Ability to Add Contacts with outdated renewal dates
Description: When adding a new contact with this command: add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 pol/123456 pt/Life r/31-12-1998 note/Basketball Player, I am allowed add him in.

Expected Behaviour: Since this platform appears to be designed for insurance agents, it might be more helpful if the system could prevent or warn users when entering renewal dates that are outdated. This could enhance data accuracy and improve the overall user experience.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: bryantjandra/ped#5

### LINKED ISSUE #210: [PE-D][Tester B] Error message for viewrenewals not specific enough
The error message in the application only shows that "NEXT_N_DAYS must be a positive number between 1 and 365". But instead, the NEXT_N_DAYS needs to be an positive Integer, which is not stated in the error message.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YosieSYX/ped#4

### LINKED ISSUE #211: [PE-D][Tester C] Renewing Policy can be renewed to an outdated date in the past
Description: When typing in the following command using the sample data: `renew pol/456789 31-12-1999`, I am able to renew. 

Expected Behaviour: Since the platform seems to be tailored for insurance agents, it might enhance user experience and data accuracy if the system could prevent or provide a gentle warning when attempting to renew policies with dates that have already passed.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: bryantjandra/ped#6

### LINKED ISSUE #215: [PE-D][Tester D] Renew doesn't change date shown immediately
Renew doesn't change date shown immediately, need to switch to other user then come back, then the date can be updated

Can lead to misunderstanding

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: e1093051/ped#8

### LINKED ISSUE #257: [PE-D][Tester B] Using Renew Command with several policy numbers
In the database I have 1 person with policy number 123457 and 1 person with policy number 123. When I put in command "renew pol/123 pol/123457 r/02-02-2025", it only renewed the person with policy number 123457. However, this is not explained by the user guide. According to logic, I should be able to renew both person with policy number 123 and person with policy number 123457. Or maybe if multiple policy numbers are not allowed, the system should return error. 

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: YosieSYX/ped#11

### PR DESCRIPTION
**Pull request by johngao122**
## Bug Fix

- Fixes #257 
- Fixes #215 
- Fixes #210 
- Fixes #211 
- Fixes #201

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PolicyTest.java [hunk 1]
```diff
@@ -206,18 +211,16 @@ public void getDaysUntilRenewal_futureDate_returnsPositiveDays() {
...
     public void getDaysUntilRenewal_pastDate_returnsNegativeDays() {
-        Policy policy = new Policy(
-            "123456",
-            new RenewalDate(LocalDate.now()
-                .minusDays(5)
-                .format(RenewalDate.DATE_FORMATTER)));
-        assertEquals(-5, policy.getDaysUntilRenewal());
+        // We can't test past dates since they're invalid for RenewalDate
+        // This test is no longer applicable
+        assertTrue(true);
```
Comment (Jovin-Ang) [inline src/test/java/seedu/address/model/person/PolicyTest.java]: Are we keeping tests that are no longer applicable? Or should we remove it completely?

**Review by Jovin-Ang — DISMISSED** [review]
LGTM, LGTM
Looks good to me, Looks good to merge :)

Do check out the comments above and by copilot before merging though and see if they are applicable

File: src/test/java/seedu/address/model/person/PolicyTest.java (hunk 1 above)
Comment (johngao122) [reply src/test/java/seedu/address/model/person/PolicyTest.java]: I will remove them

File: src/main/java/seedu/address/logic/commands/RenewCommand.java [hunk 2]
```diff
@@ -53,20 +51,18 @@ public RenewCommand(String policyNumber, RenewalDate newRenewalDate) {
...
+
+        if (matchingPersons.isEmpty()) {
             throw new CommandException(String.format(MESSAGE_POLICY_NOT_FOUND, policyNumber));
         }
-        if (filteredPersons.size() > 1) {
+        if (matchingPersons.size() > 1) {
             throw new CommandException(String.format(MESSAGE_MULTIPLE_POLICIES, policyNumber));
         }
-        Person personToUpdate = filteredPersons.get(0);
+        Person personToUpdate = matchingPersons.get(0);
```
Comment (MakiseKurisuX) [inline src/main/java/seedu/address/logic/commands/RenewCommand.java:65]: Can you write justification as an in-line comment for this line?

**Review by MakiseKurisuX — CHANGES_REQUESTED** [review]
That is the only comment. Everything LGTM otherwise.

File: src/main/java/seedu/address/logic/commands/RenewCommand.java (hunk 2 above)
Comment (johngao122) [reply src/main/java/seedu/address/logic/commands/RenewCommand.java:65]: Changed

Comment (johngao122) [reply src/main/java/seedu/address/logic/commands/RenewCommand.java:65]: image

**Review by MakiseKurisuX — APPROVED** [review]
LGTM
